// build.rs
//! A build script for the `jophet` compiler crate.
//!
//! This script runs at compile-time when building the `jophet` executable itself.
//! Its purpose is to capture the host's target triple (e.g., `x86_64-pc-windows-msvc`)
//! from the environment variables provided by Cargo.
//!
//! It then sets a new compile-time environment variable, `JOPHET_HOST_TRIPLE`, which
//! becomes available to the main compiler source code via `env! JOPHET_HOST_TRIPLE)`.
//! This is crucial for ensuring that the C code generated by the Jophet compiler is
//! compiled by the `cc` crate to target the same architecture as the compiler itself,
//! enabling cross-compilation if the host Rust compiler is set up for it.

use std::env;

fn main() {
    // This script runs when compiling the `jophet` binary.
    // It captures the HOST triple from Cargo's environment...
    let host_triple = env::var("HOST").unwrap();
    // ...and sets a new compile-time environment variable for our main source code to use.
    println!("cargo:rustc-env=JOPHET_HOST_TRIPLE={}", host_triple);
}