// src/commands/install.rs
//! Handles the `jophet install` command.
//!
//! This command builds the current project in release mode and copies the final
//! artifact to a shared location in the user's home directory (`~/.jophet`).
//!
//! - For binary projects, the executable is copied to `~/.jophet/bin/`.
//! - For library projects, the static library (`.a` or `.lib`) is copied to
//!   `~/.jophet/lib/`, the public API metadata is copied to `~/.jophet/meta/`,
//!   and any public header files generated by the backend are copied to
//!   `~/.jophet/include/`. This makes the library available for other Jophet
//!   projects to link against.
//!
//! This module now enforces the standard library entry point convention (`src/lib.jophet`).

use crate::backend::{self, BackendType, OutputFileType};
use crate::commands::build::{self, MultipleErrors};
use crate::config;
use crate::diagnostics;
use std::env;
use std::error::Error;
use std::fs;
use std::path::Path;

/// The main entry point for the `install` command.
///
/// It determines the project type from `Jophet.toml`, creates the necessary
/// directories in `~/.jophet`, invokes the build process, and copies the
/// resulting artifacts to their final destinations. It always performs a release
/// build and now also defaults to a static build for executables.
pub fn handle_install() -> Result<(), Box<dyn Error>> {
    diagnostics::print_installing();

    let (config, project_root) = config::load_config()?;
    let home_dir = home::home_dir().ok_or("Could not find home directory.")?;
    let jophet_home = home_dir.join(".jophet");

    // The `install` command always targets the host machine.
    let host_triple = env!("JOPHET_HOST_TRIPLE");
    let is_windows_target = host_triple.contains("windows");

    if config.package.r#type == "lib" {
        // Set up directories for installed libraries, includes, and metadata.
        let jophet_lib_dir = jophet_home.join("lib");
        let jophet_include_dir = jophet_home.join("include");
        let jophet_meta_dir = jophet_home.join("meta");

        fs::create_dir_all(&jophet_lib_dir)?;
        fs::create_dir_all(&jophet_include_dir)?;
        fs::create_dir_all(&jophet_meta_dir)?;

        // Ensure the C runtime header is available for any project to include,
        // as installed libraries might depend on it.
        let runtime_h_content = include_str!("../backend/c/runtime.h");
        fs::write(jophet_include_dir.join("runtime.h"), runtime_h_content)?;

        // Build the library in release mode, enabling the `is_installing` flag
        // to trigger metadata generation. Libraries are inherently static.
        // We pass `None` for target, so it defaults to the host.
        let artifact = build::handle_build(true, true, false, None, true, None)?;
        let artifact_path = &artifact.path;

        // The build process generates all necessary files, including public headers.
        // We now need to re-run the backend (not a full build) to get those files
        // and copy them to the install directory.
        
        // Correctly determine the entry point for a library package.
        let entry_point_file = project_root.join("src").join("lib.jophet");
        if !entry_point_file.exists() {
            return Err(format!("Library entry point not found at '{}'. For a library package, the entry point must be `src/lib.jophet`.", entry_point_file.display()).into());
        }

        let source_code = fs::read_to_string(&entry_point_file)?;

        // Create a dummy deps dir since we are not building dependencies here.
        let profile_name = "release";
        let shared_deps_dir = project_root
            .join("target")
            .join(profile_name)
            .join("deps");
        fs::create_dir_all(&shared_deps_dir)?;

        // For this re-analysis, we default to the host target.
        let target_info = backend::resolve_target_info(host_triple)?;

        let analysis_result = crate::core::run_frontend(
            &source_code,
            project_root,
            entry_point_file,
            &shared_deps_dir,
            true,
            false,
            BackendType::C,
            false, // Install command is not in REPL mode
            &target_info,
        )
        .map_err(|errors| -> Box<dyn Error> { Box::new(MultipleErrors(errors)) })?;

        let backend = backend::get_backend(backend::BackendType::C);
        let backend_output = backend.process(
            &analysis_result.typed_program,
            &analysis_result.public_scope,
            &source_code,
            &analysis_result.module_doc_comment,
            "lib.jophet",
            &config.package.name,
            true, // is_lib is true for an install of a library
            &analysis_result.imported_modules,
            &analysis_result.all_error_defs,
            analysis_result.needs_python_runtime,
        )?;

        if let Some(headers) = backend_output.get(&OutputFileType::PublicHeader) {
            for (name, content) in headers {
                let dest_path = jophet_include_dir.join(name);
                fs::write(dest_path, content)?;
            }
        }

        // Construct the destination path with the canonical library naming convention based on the host.
        let dest_lib_path = if is_windows_target {
            jophet_lib_dir.join(format!("{}.lib", config.package.name))
        } else {
            jophet_lib_dir.join(format!("lib{}.a", config.package.name))
        };
        fs::copy(artifact_path, &dest_lib_path)?;

        diagnostics::print_installed(&config.package.name, &jophet_lib_dir);
    } else if config.package.r#type == "bin" {
        // Set up the directory for installed binaries.
        let jophet_bin_dir = jophet_home.join("bin");
        fs::create_dir_all(&jophet_bin_dir)?;

        // Build the binary in release mode with static linking, targeting the host.
        let artifact = build::handle_build(true, false, false, None, true, None)?;
        let artifact_path = &artifact.path;

        let artifact_filename = artifact_path
            .file_name()
            .ok_or("Could not get filename from build artifact path.")?;
        let dest_path = jophet_bin_dir.join(artifact_filename);

        fs::copy(artifact_path, &dest_path)?;

        // Inform the user that they may need to update their PATH.
        println!(
            "   Note: you may need to add `{}` to your system's PATH variable to run the installed binary.",
            jophet_bin_dir.display()
        );
        diagnostics::print_installed(&config.package.name, &jophet_bin_dir);
    } else {
        return Err(format!(
            "Invalid package type '{}' in Jophet.toml. Must be 'lib' or 'bin'.",
            config.package.r#type
        )
        .into());
    }

    Ok(())
}