// src/backend/c/runtime.c
/**
 * @file runtime.c
 * @brief The Jophet runtime library implementation.
 *
 * This file provides the C implementation for Jophet's built-in data types
 * and helper functions. It includes the logic for dynamic strings (`JophetString`),
 * generic vectors (`JophetVector`), and various utility functions for string building
 * and formatting. This runtime is linked with the C code generated by the Jophet
 * compiler to provide essential functionality.
 */

#define _USE_MATH_DEFINES // For M_PI on MSVC

// Disable specific MSVC warnings for this file.
// C4996: 'strerror' may be unsafe. This is a portability concern that we accept for now.
// C4255: no function prototype given. This is for the empty fn_ptr in JophetClosure.
// C4820: bytes padding added after data member. This is expected and normal for struct alignment.
#ifdef _MSC_VER
#pragma warning(disable : 4996 4255 4820)
#endif

#include "runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <stdarg.h>
#include <math.h>
#include <ctype.h>

#if !defined(_WIN32) && !defined(_WIN64)
#include <sys/wait.h> // For WIFEXITED and WEXITSTATUS on POSIX systems
#endif


// --- Utility Functions ---

/**
 * @brief Allocates a block of memory of the given size.
 *
 * This function is an unsafe wrapper around `malloc`. It is intended to be called
 * only from within an `allow` block in Jophet.
 *
 * @param size The number of bytes to allocate.
 * @return A void pointer to the allocated memory, or NULL if allocation fails.
 */
void* jophet_allocate(size_t size) {
    return malloc(size);
}

/**
 * @brief Deallocates a block of memory.
 *
 * This function is an unsafe wrapper around `free`. It is intended to be called
 * only from within an `allow` block in Jophet.
 *
 * @param ptr A void pointer to the memory to deallocate.
 */
void jophet_deallocate(void* ptr) {
    free(ptr);
}

/**
 * @brief Performs a runtime bounds check for array and vector access.
 *
 * This function checks if the given `index` is within the valid range [0, length).
 * If the index is out of bounds, it prints a fatal error message to stderr, including
 * source file and line information, and then terminates the program with a non-zero
 * exit code. If the index is valid, it returns the index.
 *
 * @param index The index being accessed.
 * @param length The total number of elements in the collection.
 * @param file The name of the source file where the access occurred.
 * @param line The line number in the source file where the access occurred.
 * @return The `index` if it is valid.
 * @note This function will cause program termination on failure.
 */
size_t jophet_bounds_check(size_t index, size_t length, const char* file, int line) {
    if (index >= length) {
        // ANSI escape codes for red color and bold text
        const char* red_bold = "\x1b[1;31m";
        const char* reset = "\x1b[0m";

        fprintf(stderr, "\n%sFatal runtime error:%s index out of bounds\n", red_bold, reset);
        fprintf(stderr, "  %s-->%s %s:%d\n", "\x1b[34m", reset, file, line);
        fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);
        fprintf(stderr, "   %s|%s %sPanic:%s Accessed index %zu, but the length is only %zu.\n", "\x1b[34m", reset, red_bold, reset, index, length);
        fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);

        exit(1);
    }
    return index;
}

/**
 * @brief Handles a panic when a `try` expression fails in a non-fallible context.
 *
 * This function is called by code generated for a `try` expression that is not
 * inside a function returning a `Fallible` type. It prints a formatted fatal error
 * message, including the specific error value that caused the panic, and terminates
 * the program with a non-zero exit code.
 *
 * @param err_ptr A void pointer to the error data.
 * @param print_fn A function pointer to the appropriate `_print` function for the error's type.
 * @param file The name of the source file where the `try` expression occurred.
 * @param line The line number in the source file where the `try` expression occurred.
 * @note This function will cause program termination.
 */
void jophet_panic_on_err(const void* err_ptr, void (*print_fn)(const void*), const char* file, int line) {
    const char* red_bold = "\x1b[1;31m";
    const char* reset = "\x1b[0m";

    fprintf(stderr, "\n%sFatal runtime error:%s unhandled error\n", red_bold, reset);
    fprintf(stderr, "  %s-->%s %s:%d\n", "\x1b[34m", reset, file, line);
    fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);
    fprintf(stderr, "   %s|%s %sPanic:%s Program terminated due to an unhandled error: ", "\x1b[34m", reset, red_bold, reset);
    print_fn(err_ptr);
    fprintf(stderr, "\n   %s|%s\n", "\x1b[34m", reset);

    exit(1);
}

/**
 * @brief Handles a panic with a simple string message.
 *
 * This function is a convenience for runtime errors that don't have a structured
 * error type, such as calling `minimum` on an empty collection.
 *
 * @param message The error message to display.
 * @param file The name of the source file where the error occurred.
 * @param line The line number in the source file where the error occurred.
 * @note This function will cause program termination.
 */
void jophet_panic_on_err_message(const char* message, const char* file, int line) {
    const char* red_bold = "\x1b[1;31m";
    const char* reset = "\x1b[0m";

    fprintf(stderr, "\n%sFatal runtime error:%s %s\n", red_bold, reset, message);
    fprintf(stderr, "  %s-->%s %s:%d\n", "\x1b[34m", reset, file, line);
    fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);
    fprintf(stderr, "   %s|%s %sPanic:%s %s\n", "\x1b[34m", reset, red_bold, reset, message);
    fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);

    exit(1);
}

/**
 * @brief Handles a panic when a Python FFI call fails.
 *
 * This function prints a formatted fatal error message including the Python exception
 * details and source location of the FFI call, then terminates the program.
 *
 * @param py_err_msg A pointer to a JophetString containing the Python exception message.
 * @param file The name of the source file where the FFI call occurred.
 * @param line The line number in the source file where the FFI call occurred.
 * @note This function will cause program termination.
 */
void jophet_panic_on_py_err(const JophetString* py_err_msg, const char* file, int line) {
    const char* red_bold = "\x1b[1;31m";
    const char* reset = "\x1b[0m";

    fprintf(stderr, "\n%sFatal runtime error:%s unhandled Python exception\n", red_bold, reset);
    fprintf(stderr, "  %s-->%s %s:%d\n", "\x1b[34m", reset, file, line);
    fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);
    fprintf(stderr, "   %s|%s %sPanic:%s An FFI call failed with the following Python error:\n", "\x1b[34m", reset, red_bold, reset);
    fprintf(stderr, "   %s|%s %s%.*s%s\n", "\x1b[34m", reset, red_bold, (int)py_err_msg->len, py_err_msg->data, reset);
    fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);

    exit(1);
}


// --- Built-in String Type Implementation ---

/**
 * @brief Ensures a JophetString has enough capacity for an additional length.
 *
 * If the current capacity is insufficient to hold `s->len + additional_len`,
 * this function reallocates the string's data buffer. The new capacity is
 * doubled until it's large enough. The reallocation strategy uses a growth
 * factor of 2 to achieve amortized O(1) appends.
 *
 * @param s A pointer to the JophetString to modify.
 * @param additional_len The number of additional bytes required.
 * @note This function will exit the program if reallocation fails.
 */
static void String_ensure_capacity(JophetString* s, size_t additional_len) {
    if (s->len + additional_len > s->capacity) {
        size_t new_capacity = s->capacity == 0 ? 8 : s->capacity;
        while (s->len + additional_len > new_capacity) {
            new_capacity *= 2;
        }
        char* new_data = (char*)realloc(s->data, new_capacity + 1);
        if (!new_data) { exit(1); }
        s->data = new_data;
        s->capacity = new_capacity;
    }
}

/**
 * @brief Creates a new, empty JophetString.
 *
 * Initializes a JophetString with a NULL data pointer and zero length/capacity.
 * The first append operation will trigger an initial allocation.
 *
 * @return An initialized, empty JophetString.
 */
JophetString String_new(void) {
    return (JophetString){ .data = NULL, .len = 0, .capacity = 0 };
}

/**
 * @brief Creates a new JophetString from a null-terminated C string.
 *
 * Allocates memory and copies the content of the C string. The new
 * JophetString will own its data.
 *
 * @param c_str The null-terminated C string to copy.
 * @return A new JophetString containing a copy of c_str.
 * @note This function will exit the program if memory allocation fails.
 */
JophetString String_new_from(const char* c_str) {
    size_t len = strlen(c_str);
    char* new_data = (char*)malloc(len + 1);
    if (!new_data) { exit(1); }
    memcpy(new_data, c_str, len);
    new_data[len] = '\0';
    return (JophetString){ .data = new_data, .len = len, .capacity = len };
}

/**
 * @brief Creates a deep copy of a JophetString.
 *
 * Allocates a new buffer and copies the contents of the source string into it.
 *
 * @param s A pointer to the JophetString to clone. The pointer should be const
 *          as the source string is not modified.
 * @return A new JophetString with its own heap-allocated data.
 * @note This function will exit the program if memory allocation fails.
 */
JophetString String_clone(const JophetString* s) {
    if (!s || !s->data) {
        return String_new();
    }
    size_t len = s->len;
    char* new_data = (char*)malloc(len + 1);
    if (!new_data) { exit(1); }
    memcpy(new_data, s->data, len);
    new_data[len] = '\0';
    return (JophetString){ .data = new_data, .len = len, .capacity = len };
}

/**
 * @brief Deallocates the memory used by a JophetString.
 *
 * Frees the internal data buffer and resets the string's fields to zero/NULL.
 * It's safe to call this on a string that has already been deleted or is zero-initialized.
 *
 * @param s A pointer to the JophetString to delete.
 */
void String_delete(JophetString* s) {
    if (s && s->data) {
        free(s->data);
        s->data = NULL;
        s->len = 0;
        s->capacity = 0;
    }
}

/**
 * @brief Gets the length of a JophetString.
 *
 * @param s A pointer to the JophetString.
 * @return The length of the string in bytes (excluding any null terminator).
 */
size_t String_length(JophetString* s) {
    return s->len;
}

/**
 * @brief Gets the character at a specific byte index in a JophetString.
 *
 * This function provides safe access to the string's data. If the index is
 * out of bounds, it returns a `Result` with `is_ok = false`.
 *
 * @param s A pointer to the JophetString. The string is not modified.
 * @param index The byte index of the character to retrieve.
 * @return A `Result_Char_Nothing` struct. If the index is in bounds, `is_ok` is true and
 *         `data.ok` contains the character. Otherwise, `is_ok` is false.
 */
Result_Char_Nothing String_get(const JophetString* s, uint64_t index) {
    if (!s || index >= s->len) {
        return (Result_Char_Nothing){ .is_ok = false };
    }
    return (Result_Char_Nothing){ .is_ok = true, .data.ok = s->data[index] };
}

/**
 * @brief Splits a string into a vector of its characters.
 * 
 * Creates a new `JophetVector` where each element is a `char` from the source string.
 * This is a non-UTF8-aware, byte-wise split.
 *
 * @param s A pointer to the source JophetString. The string is not modified.
 * @return A new JophetVector containing each character from the source string.
 */
JophetVector String_characters(const JophetString* s) {
    JophetVector vec = Vector_new(sizeof(char));
    if (!s || !s->data) {
        return vec;
    }

    for (size_t i = 0; i < s->len; ++i) {
        Vector_push(&vec, &s->data[i]);
    }
    return vec;
}

/**
 * @brief Checks if a string is empty.
 * @param s A pointer to the JophetString.
 * @return `true` if the string length is 0, `false` otherwise.
 */
bool String_isEmpty(const JophetString* s) {
    return s == NULL || s->len == 0;
}

/**
 * @brief Removes and returns the last character of a string.
 * @param s A pointer to the JophetString to modify.
 * @return A `Result_Char_Nothing`. If the string was not empty, `is_ok` is true and `data.ok`
 *         contains the removed character. Otherwise, `is_ok` is false.
 */
Result_Char_Nothing String_pop(JophetString* s) {
    if (s == NULL || s->len == 0) {
        return (Result_Char_Nothing){ .is_ok = false };
    }
    // Correct logic: get char at len - 1 BEFORE decrementing.
    char last_char = s->data[s->len - 1];
    s->len--;
    s->data[s->len] = '\0';
    return (Result_Char_Nothing){ .is_ok = true, .data.ok = last_char };
}

/**
 * @brief Returns the first character of a string without removing it.
 * @param s A pointer to the JophetString.
 * @return A `Result_Char_Nothing`. If the string is not empty, `is_ok` is true and `data.ok`
 *         contains the first character. Otherwise, `is_ok` is false.
 */
Result_Char_Nothing String_first(const JophetString* s) {
    if (s == NULL || s->len == 0) {
        return (Result_Char_Nothing){ .is_ok = false };
    }
    return (Result_Char_Nothing){ .is_ok = true, .data.ok = s->data[0] };
}

/**
 * @brief Returns the last character of a string without removing it.
 * @param s A pointer to the JophetString.
 * @return A `Result_Char_Nothing`. If the string is not empty, `is_ok` is true and `data.ok`
 *         contains the last character. Otherwise, `is_ok` is false.
 */
Result_Char_Nothing String_last(const JophetString* s) {
    if (s == NULL || s->len == 0) {
        return (Result_Char_Nothing){ .is_ok = false };
    }
    return (Result_Char_Nothing){ .is_ok = true, .data.ok = s->data[s->len - 1] };
}

/**
 * @brief Checks if a string contains a given substring.
 * @param s A pointer to the JophetString to search within.
 * @param substring A pointer to the JophetString to search for.
 * @return `true` if the substring is found, `false` otherwise.
 */
bool String_contains(const JophetString* s, const JophetString* substring) {
    if (s == NULL || s->data == NULL || substring == NULL || substring->data == NULL) {
        return false;
    }
    return strstr(s->data, substring->data) != NULL;
}


// --- Char Utilities ---

/**
 * @brief Checks if a character is alphanumeric (a-z, A-Z, 0-9).
 *
 * This function wraps the standard C `isalnum` function for use as a built-in
 * method in Jophet.
 *
 * @param c The character to check.
 * @return `true` if the character is a letter or a digit, `false` otherwise.
 */
bool jophet_char_is_alphanumeric(char c) {
    return isalnum((unsigned char)c) != 0;
}

/**
 * @brief Checks if a character is alphabetic (a-z, A-Z).
 *
 * This function wraps the standard C `isalpha` function for use as a built-in
 * method in Jophet.
 *
 * @param c The character to check.
 * @return `true` if the character is a letter, `false` otherwise.
 */
bool jophet_char_is_alphabetic(char c) {
    return isalpha((unsigned char)c) != 0;
}

/**
 * @brief Checks if a character is a digit (0-9).
 *
 * This function wraps the standard C `isdigit` function for use as a built-in
 * method in Jophet.
 *
 * @param c The character to check.
 * @return `true` if the character is a digit, `false` otherwise.
 */
bool jophet_char_is_digit(char c) {
    return isdigit((unsigned char)c) != 0;
}

/**
 * @brief Checks if a character is whitespace (space, tab, newline, etc.).
 *
 * This function wraps the standard C `isspace` function for use as a built-in
 * method in Jophet.
 *
 * @param c The character to check.
 * @return `true` if the character is a whitespace character, `false` otherwise.
 */
bool jophet_char_is_whitespace(char c) {
    return isspace((unsigned char)c) != 0;
}


// --- String Formatting/Building ---

/**
 * @brief Appends a null-terminated C string to a JophetString.
 *
 * @param builder A pointer to the JophetString to which the C string will be appended.
 * @param c_str The null-terminated C string to append.
 */
void String_builder_append(JophetString* builder, const char* c_str) {
    size_t c_str_len = strlen(c_str);
    String_ensure_capacity(builder, c_str_len);
    memcpy(builder->data + builder->len, c_str, c_str_len);
    builder->len += c_str_len;
    builder->data[builder->len] = '\0';
}

/**
 * @brief Appends another JophetString to a JophetString.
 *
 * @param builder A pointer to the destination JophetString.
 * @param s A pointer to the source JophetString to append.
 */
void String_builder_append_string(JophetString* builder, JophetString* s) {
    String_ensure_capacity(builder, s->len);
    memcpy(builder->data + builder->len, s->data, s->len);
    builder->len += s->len;
    builder->data[builder->len] = '\0';
}

/**
 * @brief Appends a 64-bit integer to a JophetString.
 *
 * The integer is converted to its string representation before being appended.
 *
 * @param builder A pointer to the JophetString.
 * @param val The int64_t value to append.
 */
void String_builder_append_int64(JophetString* builder, int64_t val) {
    char buffer[21]; // Max length for a 64-bit integer + sign + null terminator
    int len = snprintf(buffer, sizeof(buffer), "%lld", (long long)val);
    String_ensure_capacity(builder, len);
    memcpy(builder->data + builder->len, buffer, len);
    builder->len += len;
    builder->data[builder->len] = '\0';
}

/**
 * @brief Appends a double-precision float to a JophetString.
 *
 * The double is converted to its string representation before being appended.
 * The `%g` format specifier is used to produce the most compact representation
 * and remove insignificant trailing zeros.
 *
 * @param builder A pointer to the JophetString.
 * @param val The double value to append.
 */
void String_builder_append_float64(JophetString* builder, double val) {
    char buffer[32];
    int len = snprintf(buffer, sizeof(buffer), "%g", val);
    String_ensure_capacity(builder, len);
    memcpy(builder->data + builder->len, buffer, len);
    builder->len += len;
    builder->data[builder->len] = '\0';
}

/**
 * @brief Appends a single character to a JophetString.
 *
 * @param builder A pointer to the JophetString.
 * @param val The char value to append.
 */
void String_builder_append_char(JophetString* builder, char val) {
    String_ensure_capacity(builder, 1);
    builder->data[builder->len] = val;
    builder->len++;
    builder->data[builder->len] = '\0';
}

/**
 * @brief Appends a boolean value to a JophetString.
 *
 * Appends the string "true" or "false".
 *
 * @param builder A pointer to the JophetString.
 * @param val The boolean value to append.
 */
void String_builder_append_bool(JophetString* builder, bool val) {
    const char* str = val ? "true" : "false";
    String_builder_append(builder, str);
}

/**
 * @brief A generic function to "sprint" (string print) any printable type into a builder.
 * This is a generic helper that requires a function pointer to the actual sprint implementation.
 * @param builder The string builder to append to.
 * @param data A void pointer to the data to be printed.
 * @param sprint_fn A function pointer of type `void (*)(JophetString*, const void*)`.
 */
void jophet_sprint(JophetString* builder, const void* data, void (*sprint_fn)(JophetString*, const void*)) {
    sprint_fn(builder, data);
}

// --- User Input ---

/**
 * @brief Reads a line of input from stdin.
 * 
 * Optionally prints a prompt to the user. Reads characters until a newline
 * or EOF is encountered. The returned string does not include the newline character.
 * 
 * @param prompt A null-terminated C string to display as a prompt. Can be NULL.
 * @return A new JophetString containing the user's input.
 */
JophetString input(const char* prompt) {
    if (prompt) {
        printf("%s", prompt);
        fflush(stdout);
    }

    size_t capacity = 80;
    size_t len = 0;
    char* buffer = (char*)malloc(capacity);
    if (!buffer) { exit(1); }

    int c;
    while ((c = fgetc(stdin)) != EOF && c != '\n') {
        if (len + 1 >= capacity) {
            capacity *= 2;
            char* new_buffer = (char*)realloc(buffer, capacity);
            if (!new_buffer) {
                free(buffer);
                exit(1);
            }
            buffer = new_buffer;
        }
        buffer[len++] = (char)c;
    }

    buffer[len] = '\0';
    
    // To be more memory efficient, we can realloc down to the actual size.
    char* final_buffer = (char*)realloc(buffer, len + 1);
    if (!final_buffer && len + 1 > 0) {
        // If realloc fails, the original buffer is still valid.
        return (JophetString){ .data = buffer, .len = len, .capacity = capacity };
    }

    return (JophetString){ .data = final_buffer, .len = len, .capacity = len };
}


// --- Built-in Vector Type Implementation ---

/**
 * @brief Creates a new, empty JophetVector for a given element size.
 *
 * @param elem_size The size in bytes of each element that will be stored in the vector.
 * @return An initialized, empty JophetVector.
 */
JophetVector Vector_new(size_t elem_size) {
    return (JophetVector){ .data = NULL, .len = 0, .capacity = 0, .elem_size = elem_size };
}

/**
 * @brief Creates a new JophetVector by copying data from a C array.
 *
 * Allocates a new buffer and copies `source_len` elements from the `source_data`
 * array into it. The new vector will own the copied data.
 *
 * @param elem_size The size in bytes of each element.
 * @param source_data A const void pointer to the beginning of the source C array. The data is not modified.
 * @param source_len The number of elements in the source array.
 * @return A new JophetVector containing a copy of the array data.
 * @note This function will exit the program if memory allocation fails.
 */
JophetVector Vector_new_from_array(size_t elem_size, const void* source_data, size_t source_len) {
    void* new_data = NULL;
    if (source_len > 0) {
        new_data = malloc(source_len * elem_size);
        if (!new_data) { exit(1); }
        memcpy(new_data, source_data, source_len * elem_size);
    }
    return (JophetVector){ 
        .data = new_data, 
        .len = source_len, 
        .capacity = source_len, 
        .elem_size = elem_size 
    };
}

/**
 * @brief Creates a deep copy of a JophetVector's data buffer.
 *
 * Allocates a new buffer and copies the contents of the source vector's data into it.
 *
 * @param v A pointer to the JophetVector to clone. The pointer is const as the source
 *          vector is not modified.
 * @return A new JophetVector with its own heap-allocated data.
 * @note This function performs a shallow copy of the elements themselves. If the
 *       elements contain pointers, only the pointer values are copied, not the
 *       data they point to. True deep cloning must be handled by the compiler
 *       by generating element-wise clone calls.
 * @note This function will exit the program if memory allocation fails.
 */
JophetVector Vector_clone(const JophetVector* v) {
    if (!v || !v->data) {
        return Vector_new(v ? v->elem_size : 0);
    }
    size_t len = v->len;
    size_t elem_size = v->elem_size;
    size_t total_size = len * elem_size;
    void* new_data = NULL;
    if (total_size > 0) {
        new_data = malloc(total_size);
        if (!new_data) { exit(1); }
        memcpy(new_data, v->data, total_size);
    }
    return (JophetVector){ .data = new_data, .len = len, .capacity = len, .elem_size = elem_size };
}


/**
 * @brief Deallocates the memory used by a JophetVector.
 *
 * Frees the internal data buffer and resets the vector's fields to zero/NULL.
 * It's safe to call this on a vector that has already been deleted or is zero-initialized.
 *
 * @param v A pointer to the JophetVector to delete.
 */
void Vector_delete(JophetVector* v) {
    if (v && v->data) {
        free(v->data);
        v->data = NULL;
        v->len = 0;
        v->capacity = 0;
    }
}

/**
 * @brief Pushes a new item onto the end of a JophetVector.
 *
 * This function handles reallocation if the vector's capacity is exceeded. It uses
 * a growth factor of 2 for amortized O(1) push operations. The item is copied
 * into the vector's data buffer.
 *
 * @param v A pointer to the JophetVector.
 * @param item A void pointer to the item to be pushed. The item's size must
 *             match the `elem_size` the vector was created with.
 * @note This function will exit the program if reallocation fails.
 */
void Vector_push(JophetVector* v, void* item) {
    if (v->len >= v->capacity) {
        size_t new_capacity = v->capacity == 0 ? 8 : v->capacity * 2;
        void* new_data = realloc(v->data, new_capacity * v->elem_size);
        if (!new_data) { exit(1); }
        v->data = new_data;
        v->capacity = new_capacity;
    }
    memcpy((char*)v->data + (v->len * v->elem_size), item, v->elem_size);
    v->len++;
}

/**
 * @brief Gets the number of elements in a JophetVector.
 *
 * @param v A pointer to the JophetVector.
 * @return The number of elements currently in the vector.
 */
size_t Vector_length(JophetVector* v) {
    return v->len;
}

/**
 * @brief Checks if a vector is empty.
 * @param v A pointer to the JophetVector.
 * @return `true` if the vector length is 0, `false` otherwise.
 */
bool Vector_isEmpty(const JophetVector* v) {
    return v == NULL || v->len == 0;
}

/**
 * @brief The internal implementation for popping an element. This is called by a
 *        type-safe wrapper generated by the compiler. It copies the popped element
 *        into a destination buffer.
 * @param v A pointer to the JophetVector to modify.
 * @param dest A void pointer to a buffer where the popped element will be copied.
 * @return `true` if an element was popped and copied, `false` if the vector was empty.
 */
bool Vector_pop_impl(JophetVector* v, void* dest) {
    if (v == NULL || v->len == 0) {
        return false;
    }
    v->len--; // Decrement length first
    void* last_element = (char*)v->data + (v->len * v->elem_size);
    memcpy(dest, last_element, v->elem_size);
    return true;
}

/**
 * @brief The internal implementation for peeking at the first element. This function
 *        safely copies the first element's data into a destination buffer.
 * @param v A pointer to the JophetVector.
 * @param dest A void pointer to a buffer where the first element will be copied.
 * @return `true` if an element was peeked and copied, `false` if the vector was empty.
 */
bool Vector_first_impl(const JophetVector* v, void* dest) {
    if (v == NULL || v->len == 0) {
        return false;
    }
    memcpy(dest, v->data, v->elem_size);
    return true;
}

/**
 * @brief The internal implementation for peeking at the last element. This function
 *        safely copies the last element's data into a destination buffer.
 * @param v A pointer to the JophetVector.
 * @param dest A void pointer to a buffer where the last element will be copied.
 * @return `true` if an element was peeked and copied, `false` if the vector was empty.
 */
bool Vector_last_impl(const JophetVector* v, void* dest) {
    if (v == NULL || v->len == 0) {
        return false;
    }
    void* last_element = (char*)v->data + ((v->len - 1) * v->elem_size);
    memcpy(dest, last_element, v->elem_size);
    return true;
}

/**
 * @brief Checks if a vector contains a given element.
 * @param v A pointer to the JophetVector to search within.
 * @param item A pointer to the item to search for. The comparison is done via `memcmp`.
 * @return `true` if the item is found, `false` otherwise.
 */
bool Vector_contains(const JophetVector* v, const void* item) {
    if (v == NULL || v->len == 0) {
        return false;
    }
    for (size_t i = 0; i < v->len; ++i) {
        void* current_item = (char*)v->data + (i * v->elem_size);
        if (memcmp(current_item, item, v->elem_size) == 0) {
            return true;
        }
    }
    return false;
}

static size_t jophet_normalize_slice_bound(size_t bound, size_t len) {
    return bound > len ? len : bound;
}

JophetVector jophet_slice_shallow(const void* data_ptr, size_t original_len, size_t elem_size, size_t start, size_t end, const char* file, int line) {
    (void)file; (void)line; // Currently unused, but kept for API consistency
    
    size_t final_start = jophet_normalize_slice_bound(start, original_len);
    size_t final_end = jophet_normalize_slice_bound(end, original_len);

    if (final_start >= final_end) {
        return Vector_new(elem_size);
    }

    size_t slice_len = final_end - final_start;
    size_t slice_size_bytes = slice_len * elem_size;

    void* new_data = malloc(slice_size_bytes);
    if (!new_data) { exit(1); }

    const char* source_ptr = (const char*)data_ptr + (final_start * elem_size);
    memcpy(new_data, source_ptr, slice_size_bytes);

    return (JophetVector){
        .data = new_data,
        .len = slice_len,
        .capacity = slice_len,
        .elem_size = elem_size
    };
}

JophetVector jophet_slice_deep(const void* data_ptr, size_t original_len, size_t elem_size, size_t start, size_t end, Jophet_Item_Clone_Fn clone_fn, const char* file, int line) {
    (void)file; (void)line;
    
    size_t final_start = jophet_normalize_slice_bound(start, original_len);
    size_t final_end = jophet_normalize_slice_bound(end, original_len);

    JophetVector new_vec = Vector_new(elem_size);

    if (final_start >= final_end) {
        return new_vec;
    }

    for (size_t i = final_start; i < final_end; ++i) {
        const void* src_item_ptr = (const char*)data_ptr + (i * elem_size);
        void* cloned_item = clone_fn(src_item_ptr); // clone_fn returns a new heap-allocated item
        if (!cloned_item) { exit(1); }
        Vector_push(&new_vec, cloned_item);
        
        // Note on memory management:
        // 1. `clone_fn` (a thunk generated by the Jophet compiler) allocates a new temporary
        //    container for the element on the heap (e.g., `malloc(sizeof(JophetString))`).
        //    It then performs a deep copy of the source element's *contents* into this container.
        // 2. `Vector_push` performs a `memcpy` of this container struct into the vector's data buffer.
        //    The vector now owns the deep-copied data (e.g., the `char*` inside the `JophetString`).
        // 3. `free(cloned_item)` deallocates only the temporary container, not the deep-copied data
        //    it points to, thus preventing a double-free when the vector is later deleted.
        free(cloned_item); 
    }
    
    return new_vec;
}

JophetString jophet_string_slice(const void* data_ptr, size_t original_len, size_t elem_size, size_t start, size_t end, Jophet_Item_Clone_Fn clone_fn, const char* file, int line) {
    (void)elem_size; (void)clone_fn; (void)file; (void)line;
    
    size_t final_start = jophet_normalize_slice_bound(start, original_len);
    size_t final_end = jophet_normalize_slice_bound(end, original_len);

    if (final_start >= final_end) {
        return String_new();
    }

    size_t slice_len = final_end - final_start;
    char* new_data = (char*)malloc(slice_len + 1);
    if (!new_data) { exit(1); }

    memcpy(new_data, (const char*)data_ptr + final_start, slice_len);
    new_data[slice_len] = '\0';

    return (JophetString){
        .data = new_data,
        .len = slice_len,
        .capacity = slice_len
    };
}

JophetVector jophet_flatten_impl(const void* collection, size_t outer_len, Jophet_Inner_Len_Fn inner_len_fn, size_t elem_size, Jophet_Inner_Data_Fn inner_data_fn, Jophet_Item_Clone_Fn clone_fn) {
    JophetVector result_vec = Vector_new(elem_size);

    for (size_t i = 0; i < outer_len; ++i) {
        // The pointer arithmetic to get the inner collection depends on its size.
        // The generated wrapper will pass the correct pointer.
        // The `inner_data_fn(NULL)` trick is to get the size of the inner collection type for pointer arithmetic.
        size_t inner_collection_size = (size_t)inner_data_fn(NULL);
        const void* inner_collection = (const char*)collection + (i * inner_collection_size);
        
        size_t current_inner_len = inner_len_fn(inner_collection);
        const void* inner_data = inner_data_fn(inner_collection);

        if (clone_fn) {
            for (size_t j = 0; j < current_inner_len; ++j) {
                const void* src_item_ptr = (const char*)inner_data + (j * elem_size);
                void* cloned_item_container = clone_fn(src_item_ptr);
                if (!cloned_item_container) { 
                    fprintf(stderr, "Fatal runtime error: Failed to allocate memory during flatten (cloning).\n");
                    exit(1);
                }
                Vector_push(&result_vec, cloned_item_container);
                free(cloned_item_container);
            }
        } else {
            // Shallow copy for primitives
            size_t bytes_to_copy = current_inner_len * elem_size;
            if (bytes_to_copy > 0) {
                 if (result_vec.len + current_inner_len > result_vec.capacity) {
                    size_t new_capacity = result_vec.capacity;
                    if (new_capacity == 0) new_capacity = 8;
                    while (result_vec.len + current_inner_len > new_capacity) {
                        new_capacity *= 2;
                    }
                    void* new_data = realloc(result_vec.data, new_capacity * elem_size);
                    if (!new_data) { 
                        fprintf(stderr, "Fatal runtime error: Failed to allocate memory during flatten (realloc).\n");
                        exit(1);
                     }
                    result_vec.data = new_data;
                    result_vec.capacity = new_capacity;
                }
                memcpy((char*)result_vec.data + (result_vec.len * elem_size), inner_data, bytes_to_copy);
                result_vec.len += current_inner_len;
            }
        }
    }
    return result_vec;
}


// --- String Parsing ---

// Helper macro to generate parsing functions for different integer types.
#define PARSE_INT_FUNCTION(name, type, str_to_t, min_val, max_val, result_type) \
result_type name(const JophetString* s) { \
    if (!s || !s->data) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    char* end; \
    errno = 0; \
    long long val = str_to_t(s->data, &end, 10); \
    if (errno == ERANGE || val < min_val || val > max_val) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_OutOfRange } }; \
    } \
    if (end == s->data || *end != '\0') { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    return (result_type){ .is_ok = true, .data.ok = (type)val }; \
}

// Helper macro for unsigned integers
#define PARSE_UINT_FUNCTION(name, type, str_to_t, max_val, result_type) \
result_type name(const JophetString* s) { \
    if (!s || !s->data) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    if (s->data[0] == '-') { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    char* end; \
    errno = 0; \
    unsigned long long val = str_to_t(s->data, &end, 10); \
    if (errno == ERANGE || val > max_val) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_OutOfRange } }; \
    } \
    if (end == s->data || *end != '\0') { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    return (result_type){ .is_ok = true, .data.ok = (type)val }; \
}

// Helper macro for floating point types
#define PARSE_FLOAT_FUNCTION(name, type, str_to_t, result_type) \
result_type name(const JophetString* s) { \
    if (!s || !s->data) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    char* end; \
    errno = 0; \
    type val = str_to_t(s->data, &end); \
    if (errno == ERANGE) { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_OutOfRange } }; \
    } \
    if (end == s->data || *end != '\0') { \
        return (result_type){ .is_ok = false, .data.err = { .tag = ParseError_InvalidFormat } }; \
    } \
    return (result_type){ .is_ok = true, .data.ok = val }; \
}


// Generate the functions using the macros
PARSE_INT_FUNCTION(parse_int8, int8_t, strtoll, INT8_MIN, INT8_MAX, Result_int8_t_ParseError)
PARSE_INT_FUNCTION(parse_int16, int16_t, strtoll, INT16_MIN, INT16_MAX, Result_int16_t_ParseError)
PARSE_INT_FUNCTION(parse_int32, int32_t, strtoll, INT32_MIN, INT32_MAX, Result_int32_t_ParseError)
PARSE_INT_FUNCTION(parse_int64, int64_t, strtoll, LLONG_MIN, LLONG_MAX, Result_int64_t_ParseError)

PARSE_UINT_FUNCTION(parse_uint8, uint8_t, strtoull, UINT8_MAX, Result_uint8_t_ParseError)
PARSE_UINT_FUNCTION(parse_uint16, uint16_t, strtoull, UINT16_MAX, Result_uint16_t_ParseError)
PARSE_UINT_FUNCTION(parse_uint32, uint32_t, strtoull, UINT32_MAX, Result_uint32_t_ParseError)
PARSE_UINT_FUNCTION(parse_uint64, uint64_t, strtoull, ULLONG_MAX, Result_uint64_t_ParseError)

PARSE_FLOAT_FUNCTION(parse_float32, float, strtof, Result_float_ParseError)
PARSE_FLOAT_FUNCTION(parse_float64, double, strtod, Result_double_ParseError)


// --- File I/O Implementation ---

Result_JophetString_IoError jophet_read(const JophetString* path) {
    if (!path || !path->data) {
        JophetString msg = String_new_from("File path cannot be null");
        return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    FILE* file = fopen(path->data, "rb");
    if (!file) {
        if (errno == ENOENT) {
            return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_NotFound } };
        } else if (errno == EACCES) {
            return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_AccessDenied } };
        }
        char err_buf[256];
        snprintf(err_buf, sizeof(err_buf), "Could not open file '%s': %s", path->data, strerror(errno));
        JophetString msg = String_new_from(err_buf);
        return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    fseek(file, 0, SEEK_END);
    long file_size = ftell(file);
    fseek(file, 0, SEEK_SET);

    if (file_size < 0) {
        fclose(file);
        JophetString msg = String_new_from("Could not determine file size");
        return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_ReadFailed, .data.Other = msg } };
    }

    JophetString content = String_new();
    String_ensure_capacity(&content, file_size);
    
    size_t read_size = fread(content.data, 1, file_size, file);
    fclose(file);

    if (read_size != (size_t)file_size) {
        String_delete(&content);
        return (Result_JophetString_IoError){ .is_ok = false, .data.err = { .tag = IoError_ReadFailed } };
    }
    
    content.len = file_size;
    content.data[content.len] = '\0';

    return (Result_JophetString_IoError){ .is_ok = true, .data.ok = content };
}

#if defined(_WIN32) || defined(_WIN64)
Result_JophetVector_IoError jophet_read_lines(const JophetString* path) {
    if (!path || !path->data) {
        JophetString msg = String_new_from("File path cannot be null");
        return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    FILE* file = fopen(path->data, "r");
    if (!file) {
        if (errno == ENOENT) {
            return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_NotFound } };
        } else if (errno == EACCES) {
            return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_AccessDenied } };
        }
        char err_buf[256];
        snprintf(err_buf, sizeof(err_buf), "Could not open file '%s': %s", path->data, strerror(errno));
        JophetString msg = String_new_from(err_buf);
        return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    JophetVector lines = Vector_new(sizeof(JophetString));
    char buffer[4096];

    while (fgets(buffer, sizeof(buffer), file)) {
        size_t len = strlen(buffer);
        if (len > 0 && buffer[len - 1] == '\n') {
            buffer[len - 1] = '\0';
        }
        JophetString j_line = String_new_from(buffer);
        Vector_push(&lines, &j_line);
    }
    
    fclose(file);

    return (Result_JophetVector_IoError){ .is_ok = true, .data.ok = lines };
}
#else
Result_JophetVector_IoError jophet_read_lines(const JophetString* path) {
    if (!path || !path->data) {
        JophetString msg = String_new_from("File path cannot be null");
        return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    FILE* file = fopen(path->data, "r");
     if (!file) {
        if (errno == ENOENT) {
            return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_NotFound } };
        } else if (errno == EACCES) {
            return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_AccessDenied } };
        }
        char err_buf[256];
        snprintf(err_buf, sizeof(err_buf), "Could not open file '%s': %s", path->data, strerror(errno));
        JophetString msg = String_new_from(err_buf);
        return (Result_JophetVector_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    JophetVector lines = Vector_new(sizeof(JophetString));
    char* line_buf = NULL;
    size_t line_cap = 0;
    ssize_t line_len;

    while ((line_len = getline(&line_buf, &line_cap, file)) != -1) {
        if (line_len > 0 && line_buf[line_len - 1] == '\n') {
            line_buf[line_len - 1] = '\0';
        }
        JophetString j_line = String_new_from(line_buf);
        Vector_push(&lines, &j_line);
    }
    
    free(line_buf);
    fclose(file);

    return (Result_JophetVector_IoError){ .is_ok = true, .data.ok = lines };
}
#endif

Result_void_IoError jophet_write(const JophetString* path, const JophetString* content) {
    if (!path || !path->data) {
        JophetString msg = String_new_from("File path cannot be null");
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }
     if (!content || !content->data) {
        // Allow writing an empty string, but not a null one.
        FILE* file = fopen(path->data, "wb");
        if (!file) {
            return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_WriteFailed } };
        }
        fclose(file);
        return (Result_void_IoError){ .is_ok = true };
    }

    FILE* file = fopen(path->data, "wb");
    if (!file) {
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_WriteFailed } };
    }

    size_t written = fwrite(content->data, 1, content->len, file);
    fclose(file);

    if (written != content->len) {
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_WriteFailed } };
    }
    
    return (Result_void_IoError){ .is_ok = true };
}

Result_void_IoError jophet_write_lines(const JophetString* path, const JophetVector* lines) {
     if (!path || !path->data) {
        JophetString msg = String_new_from("File path cannot be null");
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }
     if (!lines) {
        JophetString msg = String_new_from("Lines vector cannot be null");
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_Other, .data.Other = msg } };
    }

    FILE* file = fopen(path->data, "w");
     if (!file) {
        return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_WriteFailed } };
    }

    for (size_t i = 0; i < lines->len; i++) {
        JophetString* line = &(((JophetString*)lines->data)[i]);
        if (fprintf(file, "%.*s\n", (int)line->len, line->data) < 0) {
            fclose(file);
             return (Result_void_IoError){ .is_ok = false, .data.err = { .tag = IoError_WriteFailed } };
        }
    }

    fclose(file);
    return (Result_void_IoError){ .is_ok = true };
}


// --- System Commands ---

Result_int32_t_CommandError jophet_command(int num_commands, ...) {
    va_list args;
    va_start(args, num_commands);

    int last_exit_code = 0;

    for (int i = 0; i < num_commands; ++i) {
        const JophetString* cmd_str = va_arg(args, const JophetString*);

        if (!cmd_str || !cmd_str->data) {
            va_end(args);
            return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_NotFound } };
        }

        int system_ret = system(cmd_str->data);
        
        #if defined(_WIN32) || defined(_WIN64)
            // On Windows, system() returns the command's exit code directly.
            // A value of -1 indicates an error spawning the command interpreter itself.
            if (system_ret == -1) {
                va_end(args);
                return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_Failed, .data.Failed = -1 } };
            }
            if (system_ret != 0) {
                va_end(args);
                return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_Failed, .data.Failed = system_ret } };
            }
            last_exit_code = system_ret;
        #else
            // On POSIX, the return value needs to be decoded.
            if (system_ret == -1) {
                // This means fork() or exec() failed.
                va_end(args);
                return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_Failed, .data.Failed = -1 } };
            }
            
            if (WIFEXITED(system_ret)) {
                int exit_status = WEXITSTATUS(system_ret);
                if (exit_status != 0) {
                    va_end(args);
                    return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_Failed, .data.Failed = exit_status } };
                }
                last_exit_code = exit_status;
            } else {
                // The command terminated abnormally (e.g., by a signal).
                va_end(args);
                return (Result_int32_t_CommandError){ .is_ok = false, .data.err = { .tag = CommandError_TerminatedAbnormally } };
            }
        #endif
    }

    va_end(args);

    // All commands succeeded. Return the exit code of the last one.
    return (Result_int32_t_CommandError){ .is_ok = true, .data.ok = (int32_t)last_exit_code };
}


// --- Math ---

/**
 * @brief Computes integer exponentiation with runtime safety checks.
 *
 * Calculates `base` to the power of `exp`. This function uses an efficient
 * exponentiation by squaring algorithm. It panics if the exponent is negative,
 * as this is disallowed for integer exponentiation in Jophet and indicates a
 * logic error that bypassed the compiler's static checks.
 *
 * @param base The base of the operation.
 * @param exp The non-negative exponent.
 * @param file The name of the source file where the operation occurred.
 * @param line The line number in the source file where the operation occurred.
 * @return The result of `base` raised to the power of `exp`.
 * @note This function will cause program termination on failure (negative exponent).
 */
int64_t jophet_int_pow(int64_t base, int64_t exp, const char* file, int line) {
    if (exp < 0) {
        const char* red_bold = "\x1b[1;31m";
        const char* reset = "\x1b[0m";

        fprintf(stderr, "\n%sFatal runtime error:%s integer exponentiation with negative exponent\n", red_bold, reset);
        fprintf(stderr, "  %s-->%s %s:%d\n", "\x1b[34m", reset, file, line);
        fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);
        fprintf(stderr, "   %s|%s %sPanic:%s Attempted to raise an integer to a negative power (%lld).\n", "\x1b[34m", reset, red_bold, reset, exp);
        fprintf(stderr, "   %s|%s\n", "\x1b[34m", reset);

        exit(1);
    }
    if (exp == 0) {
        return 1;
    }
    int64_t res = 1;
    while (exp > 0) {
        if (exp % 2 == 1) res *= base;
        base *= base;
        exp /= 2;
    }
    return res;
}

JophetVector jophet_collect(size_t elem_size, int arg_count, ...) {
    va_list args;
    va_start(args, arg_count);

    JophetVector vec = Vector_new(elem_size);

    if (elem_size == sizeof(int64_t)) {
        int64_t start = va_arg(args, int64_t);
        int64_t step = 1;
        int64_t stop;

        if (arg_count == 3) {
            step = va_arg(args, int64_t);
            stop = va_arg(args, int64_t);
        } else {
            stop = va_arg(args, int64_t);
        }

        if (step == 0) {
            // Avoid infinite loops
            va_end(args);
            return vec;
        }

        if (step > 0) {
            for (int64_t i = start; i <= stop; i += step) {
                Vector_push(&vec, &i);
            }
        } else { // step < 0
            for (int64_t i = start; i >= stop; i += step) {
                Vector_push(&vec, &i);
            }
        }
    } else if (elem_size == sizeof(double)) {
        double start = va_arg(args, double);
        double step = 1.0;
        double stop;

        if (arg_count == 3) {
            step = va_arg(args, double);
            stop = va_arg(args, double);
        } else {
            stop = va_arg(args, double);
        }

        if (step == 0.0) {
            va_end(args);
            return vec;
        }

        if (step > 0.0) {
            for (double i = start; i <= stop; i += step) {
                Vector_push(&vec, &i);
            }
        } else { // step < 0.0
            for (double i = start; i >= stop; i += step) {
                Vector_push(&vec, &i);
            }
        }
    }

    va_end(args);
    return vec;
}

void* __jophet_collection_minimum_or_panic(const void* data, size_t len, size_t elem_size, Jophet_Comparison_Fn compare_fn, const char* file, int line) {
    if (len == 0) {
        jophet_panic_on_err_message("Called minimum() on an empty collection.", file, line);
    }
    const char* current_min = (const char*)data;
    for (size_t i = 1; i < len; ++i) {
        const char* element = (const char*)data + (i * elem_size);
        if (compare_fn(element, current_min)) {
            current_min = element;
        }
    }
    // Return a pointer to the element within the original collection's data.
    // The caller will dereference this immediately. No new memory is allocated.
    return (void*)current_min;
}

void* __jophet_collection_maximum_or_panic(const void* data, size_t len, size_t elem_size, Jophet_Comparison_Fn compare_fn, const char* file, int line) {
    if (len == 0) {
        jophet_panic_on_err_message("Called maximum() on an empty collection.", file, line);
    }
    const char* current_max = (const char*)data;
    for (size_t i = 1; i < len; ++i) {
        const char* element = (const char*)data + (i * elem_size);
        if (compare_fn(element, current_max)) {
            current_max = element;
        }
    }
    // Return a pointer to the element within the original collection's data.
    return (void*)current_max;
}

char __jophet_string_minimum_or_panic(const char* data, size_t len, const char* file, int line) {
    if (len == 0) {
        jophet_panic_on_err_message("Called minimum() on an empty string.", file, line);
    }
    char current_min = data[0];
    for (size_t i = 1; i < len; ++i) {
        if (data[i] < current_min) {
            current_min = data[i];
        }
    }
    return current_min;
}

char __jophet_string_maximum_or_panic(const char* data, size_t len, const char* file, int line) {
    if (len == 0) {
        jophet_panic_on_err_message("Called maximum() on an empty string.", file, line);
    }
    char current_max = data[0];
    for (size_t i = 1; i < len; ++i) {
        if (data[i] > current_max) {
            current_max = data[i];
        }
    }
    return current_max;
}


// --- Built-in Dictionary Type Implementation ---

#define INITIAL_CAPACITY 16
#define LOAD_FACTOR_THRESHOLD 0.75

// Generic hash function for supported key types (integers and JophetString).
static uint64_t hash_key(const void* key, size_t key_size) {
    if (key_size == sizeof(JophetString)) {
        // FNV-1a hash for strings
        const JophetString* s = (const JophetString*)key;
        uint64_t hash = 14695981039346656037ULL;
        for (size_t i = 0; i < s->len; i++) {
            hash ^= (uint64_t)s->data[i];
            hash *= 1099511628211ULL;
        }
        return hash;
    } else {
        // FNV-1a for integer types as well for better distribution
        uint64_t hash = 14695981039346656037ULL;
        for (size_t i = 0; i < key_size; i++) {
            hash ^= ((const unsigned char*)key)[i];
            hash *= 1099511628211ULL;
        }
        return hash;
    }
}

// Generic key comparison function.
static bool compare_keys(const void* key1, const void* key2, size_t key_size) {
     if (key_size == sizeof(JophetString)) {
        const JophetString* s1 = (const JophetString*)key1;
        const JophetString* s2 = (const JophetString*)key2;
        if (s1->len != s2->len) return false;
        return memcmp(s1->data, s2->data, s1->len) == 0;
    } else {
        return memcmp(key1, key2, key_size) == 0;
    }
}

static void dictionary_resize(JophetDictionary* dict); // Forward declaration

JophetDictionary Dictionary_new(size_t key_size, size_t value_size,
                                Jophet_Item_Delete_Fn key_delete_fn, Jophet_Item_Delete_Fn value_delete_fn,
                                Jophet_Item_Clone_Fn key_clone_fn, Jophet_Item_Clone_Fn value_clone_fn) {
    JophetDictionary dict;
    dict.capacity = INITIAL_CAPACITY;
    dict.len = 0;
    dict.key_size = key_size;
    dict.value_size = value_size;
    dict.key_delete_fn = key_delete_fn;
    dict.value_delete_fn = value_delete_fn;
    dict.key_clone_fn = key_clone_fn;
    dict.value_clone_fn = value_clone_fn;
    dict.buckets = (JophetDictionaryEntry**)calloc(dict.capacity, sizeof(JophetDictionaryEntry*));
    if (!dict.buckets) { exit(1); }
    return dict;
}

void Dictionary_delete(JophetDictionary* dict) {
    if (!dict || !dict->buckets) return;
    for (size_t i = 0; i < dict->capacity; i++) {
        JophetDictionaryEntry* entry = dict->buckets[i];
        while (entry) {
            JophetDictionaryEntry* next = entry->next;
            if (dict->key_delete_fn) {
                dict->key_delete_fn(entry->key);
            }
            if (dict->value_delete_fn) {
                dict->value_delete_fn(entry->value);
            }
            free(entry->key);
            free(entry->value);
            free(entry);
            entry = next;
        }
    }
    free(dict->buckets);
    dict->buckets = NULL;
    dict->len = 0;
    dict->capacity = 0;
}

JophetDictionary Dictionary_clone(const JophetDictionary* dict) {
    if (!dict) return (JophetDictionary){0};
    JophetDictionary new_dict = Dictionary_new(dict->key_size, dict->value_size,
                                               dict->key_delete_fn, dict->value_delete_fn,
                                               dict->key_clone_fn, dict->value_clone_fn);

    for (size_t i = 0; i < dict->capacity; i++) {
        JophetDictionaryEntry* entry = dict->buckets[i];
        while (entry) {
            void* new_key;
            void* new_value;

            if (dict->key_clone_fn) {
                // The clone function returns a pointer to a new heap-allocated object
                new_key = dict->key_clone_fn(entry->key);
            } else {
                new_key = malloc(dict->key_size);
                if (!new_key) exit(1);
                memcpy(new_key, entry->key, dict->key_size);
            }

            if (dict->value_clone_fn) {
                new_value = dict->value_clone_fn(entry->value);
            } else {
                new_value = malloc(dict->value_size);
                if (!new_value) exit(1);
                memcpy(new_value, entry->value, dict->value_size);
            }
            
            // Dictionary_set copies the data from the pointers
            Dictionary_set(&new_dict, new_key, new_value);

            // Since Dictionary_set made its own copies, we must free the temporary ones we made.
            if (dict->key_clone_fn) { dict->key_delete_fn(new_key); free(new_key); } else { free(new_key); }
            if (dict->value_clone_fn) { dict->value_delete_fn(new_value); free(new_value); } else { free(new_value); }
            
            entry = entry->next;
        }
    }
    return new_dict;
}


void Dictionary_set(JophetDictionary* dict, const void* key, const void* value) {
    if (dict->len >= dict->capacity * LOAD_FACTOR_THRESHOLD) {
        dictionary_resize(dict);
    }

    uint64_t hash = hash_key(key, dict->key_size);
    size_t index = (size_t)(hash & (uint64_t)(dict->capacity - 1));

    JophetDictionaryEntry* entry = dict->buckets[index];
    while (entry) {
        if (compare_keys(entry->key, key, dict->key_size)) {
            // Key already exists, update value. First, delete the old value if necessary.
            if (dict->value_delete_fn) {
                dict->value_delete_fn(entry->value);
            }
            memcpy(entry->value, value, dict->value_size);
            return;
        }
        entry = entry->next;
    }

    // Key does not exist, create new entry
    JophetDictionaryEntry* new_entry = (JophetDictionaryEntry*)malloc(sizeof(JophetDictionaryEntry));
    if (!new_entry) { exit(1); }

    new_entry->key = malloc(dict->key_size);
    if (!new_entry) { exit(1); }
    memcpy(new_entry->key, key, dict->key_size);

    new_entry->value = malloc(dict->value_size);
    if (!new_entry->value) { exit(1); }
    memcpy(new_entry->value, value, dict->value_size);

    new_entry->next = dict->buckets[index];
    dict->buckets[index] = new_entry;
    dict->len++;
}

Result_void_ptr_void Dictionary_get(const JophetDictionary* dict, const void* key) {
    if (dict->capacity == 0) {
        return (Result_void_ptr_void){ .is_ok = false };
    }
    uint64_t hash = hash_key(key, dict->key_size);
    size_t index = (size_t)(hash & (uint64_t)(dict->capacity - 1));

    JophetDictionaryEntry* entry = dict->buckets[index];
    while (entry) {
        if (compare_keys(entry->key, key, dict->key_size)) {
            return (Result_void_ptr_void){ .is_ok = true, .data.ok = entry->value };
        }
        entry = entry->next;
    }

    return (Result_void_ptr_void){ .is_ok = false };
}

void Dictionary_print(const JophetDictionary* dict, Jophet_Item_Print_Fn key_print_fn, Jophet_Item_Print_Fn value_print_fn) {
    printf("{ ");
    bool first = true;
    for (size_t i = 0; i < dict->capacity; i++) {
        JophetDictionaryEntry* entry = dict->buckets[i];
        while (entry) {
            if (!first) {
                printf(", ");
            }
            key_print_fn(entry->key);
            printf(": ");
            value_print_fn(entry->value);
            first = false;
            entry = entry->next;
        }
    }
    printf(" }");
}

static void dictionary_resize(JophetDictionary* dict) {
    size_t old_capacity = dict->capacity;
    JophetDictionaryEntry** old_buckets = dict->buckets;
    
    dict->capacity *= 2;
    dict->buckets = (JophetDictionaryEntry**)calloc(dict->capacity, sizeof(JophetDictionaryEntry*));
    if (!dict->buckets) { exit(1); }
    dict->len = 0; // Will be recounted as we re-insert

    for (size_t i = 0; i < old_capacity; i++) {
        JophetDictionaryEntry* entry = old_buckets[i];
        while (entry) {
            JophetDictionaryEntry* next = entry->next;
            // Re-insert the existing key/value data into the new, larger table.
            // This will re-hash and place it in a new bucket.
            Dictionary_set(dict, entry->key, entry->value);
            
            // The old entry container and its key/value pointers can now be freed,
            // as Dictionary_set made new copies.
            free(entry->key);
            free(entry->value);
            free(entry);

            entry = next;
        }
    }
    
    free(old_buckets);
}

// --- Built-in Error Type Print Implementations ---

void FfiError_print(const FfiError* s) {
    const char* tag_str = "Unknown";
    switch (s->tag) {
        case FfiError_ModuleNotFound:    tag_str = "ModuleNotFound"; break;
        case FfiError_AttributeNotFound: tag_str = "AttributeNotFound"; break;
        case FfiError_ConversionFailed:  tag_str = "ConversionFailed"; break;
        case FfiError_PythonException:   tag_str = "PythonException"; break;
    }
    printf("FfiError.%s(\"", tag_str);
    // All FfiError variants carry a message payload
    printf("%.*s", (int)s->data.Message.len, s->data.Message.data);
    printf("\")");
}

void Error_print(const Error* s) {
    switch (s->tag) {
        case Error_Message: {
            printf("Error.Message(\"");
            printf("%.*s", (int)s->data.Message.len, s->data.Message.data);
            printf("\")");
            break;
        }
    }
}

void ParseError_print(const ParseError* s) {
    switch (s->tag) {
        case ParseError_InvalidFormat: {
            printf("ParseError.InvalidFormat");
            break;
        }
        case ParseError_OutOfRange: {
            printf("ParseError.OutOfRange");
            break;
        }
    }
}

void IoError_print(const IoError* s) {
    switch (s->tag) {
        case IoError_NotFound: {
            printf("IoError.NotFound");
            break;
        }
        case IoError_AccessDenied: {
            printf("IoError.AccessDenied");
            break;
        }
        case IoError_ReadFailed: {
            printf("IoError.ReadFailed");
            break;
        }
        case IoError_WriteFailed: {
            printf("IoError.WriteFailed");
            break;
        }
        case IoError_Other: {
            printf("IoError.Other(\"");
            printf("%.*s", (int)s->data.Other.len, s->data.Other.data);
            printf("\")");
            break;
        }
    }
}

void CommandError_print(const CommandError* s) {
    switch (s->tag) {
        case CommandError_Failed: {
            printf("CommandError.Failed(%d)", s->data.Failed);
            break;
        }
        case CommandError_TerminatedAbnormally: {
            printf("CommandError.TerminatedAbnormally");
            break;
        }
        case CommandError_NotFound: {
            printf("CommandError.NotFound");
            break;
        }
    }
}


// --- Built-in Closure Type Implementation ---

/**
 * @brief Deallocates a JophetClosure and its captured environment.
 *
 * If the closure has a non-NULL environment and a `delete_env_fn` function
 * pointer, this function will call the destructor to perform a deep delete of
 * the captured data before freeing the environment struct itself.
 *
 * @param c A pointer to the JophetClosure to delete.
 */
void JophetClosure_delete(JophetClosure* c) {
    if (c && c->env && c->delete_env_fn) {
        c->delete_env_fn(c->env);
        c->env = NULL;
    }
}

/**
 * @brief Creates a deep copy of a JophetClosure.
 *
 * This function creates a new JophetClosure struct and performs a deep copy
 * of its environment if a `clone_env_fn` is provided. This is crucial for
 * safely copying closures that own data.
 *
 * @param c A pointer to the JophetClosure to clone.
 * @return A new JophetClosure with its own copy of the environment.
 */
JophetClosure JophetClosure_clone(const JophetClosure* c) {
    if (!c) {
        return (JophetClosure){0};
    }
    JophetClosure new_closure;
    new_closure.fn_ptr = c->fn_ptr;
    new_closure.delete_env_fn = c->delete_env_fn;
    new_closure.clone_env_fn = c->clone_env_fn;

    // If there is an environment and a way to clone it, do so.
    if (c->env && c->clone_env_fn) {
        new_closure.env = c->clone_env_fn(c->env);
    } else {
        new_closure.env = c->env; // Handles NULL env or non-cloneable env
    }
    return new_closure;
}