// src/core/semantic_analyzer/expressions/closures.rs
//! Semantic analysis for closure expressions and capture analysis.
//!
//! This module handles the analysis of anonymous functions (closures), including the
//! complex task of determining which variables from outer scopes are "captured"
//! and need to be stored in the closure's environment. It has been updated to
//! work with the error-collecting paradigm.

use crate::core::ast::typed::*;
use crate::core::ast::untyped;
use crate::core::semantic_analyzer::{
    types::jophet_type_to_user_string, ScopeContext, SemanticAnalyzer, SymbolInfo,
};
use crate::diagnostics::errors::SemanticError;
use std::collections::{HashMap, HashSet};

impl SemanticAnalyzer<'_> {
    /// Analyzes a closure expression (`function(...) ... end`).
    ///
    /// This function performs a full analysis of the anonymous function. It determines which
    /// variables from the outer scope are "captured", creates a unique name for the
    /// underlying function, analyzes its body, and adds the resulting typed function
    /// to the list of functions to be generated by the backend. It now caches the analysis
    /// of each unique closure to avoid generating duplicate C functions.
    pub fn analyze_closure_expr(
        &mut self,
        decl: &untyped::FunctionDecl,
        ctx: &mut ScopeContext,
        span: crate::core::ast::Span,
        expected_type: Option<&JophetType>,
        errors: &mut Vec<SemanticError>,
    ) -> Result<TypedExpression, SemanticError> {
        // Use the starting position of the 'function' keyword as a unique ID for the closure's source location.
        let closure_source_id = decl.body.first().map_or(span.start, |s| s.span.start - "function".len());

        if let Some((cached_decl, cached_captures)) = self.closure_cache.get(&closure_source_id) {
            // We've analyzed this closure before. Reuse the result.
            let closure_type = JophetType::Closure {
                params: cached_decl.params.iter().skip(1).map(|(_, ty)| ty.clone()).collect(),
                ret: Box::new(cached_decl.return_type.clone()),
                mangled_name: cached_decl.mangled_name.clone(),
                env_struct_name: format!("{}_env", cached_decl.mangled_name),
            };

            if let Some(expected) = expected_type {
                 if !self.is_type_compatible(&closure_type, expected) {
                    return Err(SemanticError::TypeError {
                        message: format!(
                            "Closure type mismatch. Expected `{}`, but found `{}`.",
                            jophet_type_to_user_string(expected),
                            jophet_type_to_user_string(&closure_type)
                        ),
                        span,
                        file_path: self.current_module_path.clone(),
                    });
                }
            }

            return Ok(TypedExpression {
                kind: TypedExpressionKind::Closure {
                    function: cached_decl.clone(),
                    captures: cached_captures.clone(),
                },
                jophet_type: closure_type,
                span,
            });
        }

        let (expected_params, expected_ret) = if let Some(JophetType::Closure { params, ret, .. }) = expected_type {
            (Some(params.clone()), Some(ret.as_ref().clone()))
        } else {
            (None, None)
        };

        // Pass 1: Pre-scan the closure body to find captured variables.
        let mut captures = HashMap::new();
        let mut local_symbols = HashSet::new();
        // Add parameters to the set of local symbols.
        for (p_name, _) in &decl.params {
            local_symbols.insert(p_name.clone());
        }
        self.find_captures_in_block(&decl.body, ctx, &mut local_symbols, &mut captures)?;

        let typed_captures: Vec<TypedCapturedVariable> = captures
            .values()
            .map(|info| TypedCapturedVariable {
                name: info.0.clone(),
                jophet_type: info.1.jophet_type.clone(),
                is_mutable: info.1.is_mutable,
            })
            .collect();

        // Generate a unique mangled name for this closure's function.
        let closure_id = self.closure_counter;
        self.closure_counter += 1;
        let mangled_name = format!(
            "__jophet_closure_{}_{}",
            self.current_module_path.file_stem().unwrap().to_string_lossy(),
            closure_id
        );

        // Analyze the anonymous function declaration as if it were a normal function.
        // We pass the outer context, as the closure needs to see the variables it captures.
        let typed_func_stmt = self
            .analyze_function_like_decl(decl, ctx, None, None, Some(mangled_name.clone()), span.clone(), errors)?
            .ok_or_else(|| SemanticError::InternalError {
                message: "Closure analysis failed to produce a typed function declaration".to_string(),
                span: span.clone(),
                file_path: self.current_module_path.clone(),
            })?;

        let mut typed_decl = if let TypedStatementKind::FunctionDecl(d) = typed_func_stmt.kind {
            d
        } else {
            unreachable!()
        };

        // Attach the capture information to the function declaration itself.
        typed_decl.captures = Some(typed_captures.clone());

        // Add the newly analyzed closure function to the list of functions to be generated.
        self.monomorphized_functions.borrow_mut().insert(typed_decl.mangled_name.clone(), typed_decl.clone());

        // The type of the closure expression itself.
        // This MUST reflect the user-visible signature, WITHOUT the implicit `env` parameter.
        let closure_type = JophetType::Closure {
            params: typed_decl.params.iter().skip(1).map(|(_, ty)| ty.clone()).collect(), // Skip `env`
            ret: Box::new(typed_decl.return_type.clone()),
            mangled_name: typed_decl.mangled_name.clone(),
            // Use a sentinel name for closures with no environment.
            env_struct_name: if typed_captures.is_empty() {
                "jophet_empty_env".to_string()
            } else {
                format!("{}_env", typed_decl.mangled_name)
            },
        };

        // If there was an expected type, ensure the analyzed closure matches it.
        if let (Some(expected_params), Some(expected_ret)) = (expected_params, expected_ret) {
            if let JophetType::Closure { params: actual_params, ret: actual_ret, .. } = &closure_type {
                if *actual_params != expected_params || **actual_ret != expected_ret {
                    return Err(SemanticError::TypeError {
                        message: format!(
                            "Closure type mismatch. Expected `{}`, but found `{}`.",
                            jophet_type_to_user_string(&JophetType::Closure { params: expected_params, ret: Box::new(expected_ret), mangled_name: String::new(), env_struct_name: String::new() }),
                            jophet_type_to_user_string(&closure_type)
                        ),
                        span,
                        file_path: self.current_module_path.clone(),
                    });
                }
            }
        }
        
        self.closure_cache.insert(closure_source_id, (typed_decl.clone(), typed_captures.clone()));

        Ok(TypedExpression {
            kind: TypedExpressionKind::Closure {
                function: typed_decl,
                captures: typed_captures,
            },
            jophet_type: closure_type,
            span,
        })
    }
    
    /// Recursively traverses an untyped AST block to find all identifiers that are defined
    /// in an outer scope (`ctx`) but not in the closure's own local scope (`local_symbols`).
    pub(super) fn find_captures_in_block(
        &self,
        block: &[untyped::Statement],
        ctx: &ScopeContext,
        local_symbols: &mut HashSet<String>,
        captures: &mut HashMap<String, (String, SymbolInfo)>,
    ) -> Result<(), SemanticError> {
        for stmt in block {
            // Add newly declared variables to the set of local symbols for this closure.
            if let untyped::StatementKind::VariableDecl(decl) = &stmt.kind {
                match &decl.pattern {
                    untyped::DeclarationPattern::Identifier(name, _) => {
                        local_symbols.insert(name.clone());
                    }
                    untyped::DeclarationPattern::Tuple(targets) | untyped::DeclarationPattern::Array(targets) => {
                        for target in targets {
                            if !target.is_rest_pattern {
                                local_symbols.insert(target.var_name.clone());
                            }
                        }
                    }
                }
            }
            self.find_captures_in_statement(stmt, ctx, local_symbols, captures)?;
        }
        Ok(())
    }
    
    /// Helper to recurse through statements for capture analysis.
    pub(super) fn find_captures_in_statement(
        &self,
        stmt: &untyped::Statement,
        ctx: &ScopeContext,
        local_symbols: &mut HashSet<String>,
        captures: &mut HashMap<String, (String, SymbolInfo)>,
    ) -> Result<(), SemanticError> {
        match &stmt.kind {
            untyped::StatementKind::ExpressionStatement(expr)
            | untyped::StatementKind::Return(expr)
            | untyped::StatementKind::Yield(expr) => {
                self.find_captures_in_expr(expr, ctx, local_symbols, captures)?;
            }
            untyped::StatementKind::VariableDecl(decl) => {
                self.find_captures_in_expr(&decl.initializer, ctx, local_symbols, captures)?;
            }
            untyped::StatementKind::Assignment(_, right) => {
                self.find_captures_in_expr(right, ctx, local_symbols, captures)?;
                // Note: We don't analyze the LHS of assignment here, as it's more complex
                // and capture analysis primarily cares about reads.
            }
            untyped::StatementKind::If(if_stmt) => {
                self.find_captures_in_expr(&if_stmt.condition, ctx, local_symbols, captures)?;
                self.find_captures_in_block(&if_stmt.then_block, ctx, local_symbols, captures)?;
                if let Some(else_b) = &if_stmt.else_block {
                    match else_b.as_ref() {
                        untyped::ElseBlock::Else(stmts) => self.find_captures_in_block(stmts, ctx, local_symbols, captures)?,
                        untyped::ElseBlock::ElseIf(next_if) => {
                             // This is a bit tricky, we need to treat the `else if` as a statement.
                             // A temporary statement is created just for the recursive call.
                            let temp_stmt = untyped::Statement { kind: untyped::StatementKind::If(next_if.clone()), span: next_if.condition.span.clone() };
                            self.find_captures_in_statement(&temp_stmt, ctx, local_symbols, captures)?;
                        }
                    }
                }
            }
            untyped::StatementKind::While(while_stmt) => {
                self.find_captures_in_expr(&while_stmt.condition, ctx, local_symbols, captures)?;
                self.find_captures_in_block(&while_stmt.body, ctx, local_symbols, captures)?;
            }
            // Other statements like break, continue, import, defs don't contain expressions to check.
            _ => {}
        }
        Ok(())
    }
    
    /// Helper to recurse through expressions for capture analysis.
    pub(super) fn find_captures_in_expr(
        &self,
        expr: &untyped::Expression,
        ctx: &ScopeContext,
        local_symbols: &mut HashSet<String>,
        captures: &mut HashMap<String, (String, SymbolInfo)>,
    ) -> Result<(), SemanticError> {
        match &expr.kind {
            untyped::ExpressionKind::Identifier(name) => {
                // This is the core logic: if the identifier is not defined locally
                // but IS defined in the outer scope, it's a capture.
                if !local_symbols.contains(name) {
                    if let Some(info) = ctx.symbol_table.get(name) {
                        captures.insert(name.clone(), (name.clone(), info.clone()));
                    }
                }
            }
            untyped::ExpressionKind::BinaryOp(l, _, r) => {
                self.find_captures_in_expr(l, ctx, local_symbols, captures)?;
                self.find_captures_in_expr(r, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::UnaryOp(_, r) => {
                self.find_captures_in_expr(r, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::TernaryOp(cond, then, else_b) => {
                self.find_captures_in_expr(cond, ctx, local_symbols, captures)?;
                self.find_captures_in_expr(then, ctx, local_symbols, captures)?;
                self.find_captures_in_expr(else_b, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::FunctionCall { args, .. } => {
                for arg in args {
                    self.find_captures_in_expr(arg, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::ConstCall { args, .. } => {
                for arg in args {
                    self.find_captures_in_expr(arg, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::New { args, .. } | untyped::ExpressionKind::StructInstantiation(_, _, args) => {
                for arg in args {
                    match arg {
                        untyped::Arg::Positional(e) | untyped::Arg::Named(_, e) => self.find_captures_in_expr(e, ctx, local_symbols, captures)?,
                        untyped::Arg::KeyValuePair(k, v) => {
                             self.find_captures_in_expr(k, ctx, local_symbols, captures)?;
                             self.find_captures_in_expr(v, ctx, local_symbols, captures)?;
                        }
                    }
                }
            }
            untyped::ExpressionKind::InterpolatedString(parts) => {
                for part in parts {
                    if let untyped::InterpolationPart::Expression(e) = part {
                        self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
                    }
                }
            }
            untyped::ExpressionKind::TaggedUnionInstantiation { payload, .. } => {
                if let Some(p) = payload {
                    self.find_captures_in_expr(p, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::FieldAccess(obj, _) => {
                self.find_captures_in_expr(obj, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::MethodCall(obj, _, args) => {
                self.find_captures_in_expr(obj, ctx, local_symbols, captures)?;
                for arg in args {
                    self.find_captures_in_expr(arg, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::Tuple(elements) | untyped::ExpressionKind::ArrayLiteral(elements) => {
                for el in elements {
                    self.find_captures_in_expr(el, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::TupleAccess(obj, _) => {
                self.find_captures_in_expr(obj, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::AddressOf(e) | untyped::ExpressionKind::Dereference(e) => {
                self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::ArrayIndex { array, index } => {
                self.find_captures_in_expr(array, ctx, local_symbols, captures)?;
                self.find_captures_in_expr(index, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::ArraySlice { array, start, end } => {
                self.find_captures_in_expr(array, ctx, local_symbols, captures)?;
                if let Some(s) = start {
                    self.find_captures_in_expr(s, ctx, local_symbols, captures)?;
                }
                if let Some(e) = end {
                    self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::DictionaryInstantiation { pairs, .. } => {
                for (k, v) in pairs {
                    self.find_captures_in_expr(k, ctx, local_symbols, captures)?;
                    self.find_captures_in_expr(v, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::Switch { expression, cases, else_block } => {
                self.find_captures_in_expr(expression, ctx, local_symbols, captures)?;
                for case in cases {
                    for pattern in &case.patterns {
                        if let untyped::Pattern::Literal(e) = pattern {
                            self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
                        }
                    }
                    self.find_captures_in_block(&case.body, ctx, local_symbols, captures)?;
                }
                if let Some(block) = else_block {
                    self.find_captures_in_block(block, ctx, local_symbols, captures)?;
                }
            }
            untyped::ExpressionKind::Try(e) => {
                self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::Catch { expression, error_variable, body } => {
                self.find_captures_in_expr(expression, ctx, local_symbols, captures)?;
                let mut catch_body_locals = local_symbols.clone();
                catch_body_locals.insert(error_variable.clone());
                self.find_captures_in_block(body, ctx, &mut catch_body_locals, captures)?;
            }
            untyped::ExpressionKind::Allow(e) => {
                self.find_captures_in_expr(e, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::Convert { expr, .. } | untyped::ExpressionKind::Parse { expr, .. } => {
                self.find_captures_in_expr(expr, ctx, local_symbols, captures)?;
            }
            untyped::ExpressionKind::Literal(_)
            | untyped::ExpressionKind::EnumVariantAccess { .. }
            | untyped::ExpressionKind::Closure(_) => {}
        }
        Ok(())
    }
}